services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env:ro
      - ./cert.pem:/app/cert.pem:ro
      - ./key.pem:/app/key.pem:ro
    restart: always
    user: appuser

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend
    volumes:
      - type: tmpfs
        target: /var/cache/nginx/client_temp
      - type: tmpfs
        target: /var/cache/nginx/proxy_temp
      - type: tmpfs
        target: /var/cache/nginx/fastcgi_temp
      - type: tmpfs
        target: /var/cache/nginx/uwsgi_temp
      - type: tmpfs
        target: /var/cache/nginx/scgi_temp
      - type: tmpfs
        target: /run/nginx